In [10]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [16]:
# write your code here ^_^
x = np.ones(4)
x

array([1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [24]:
# write your code here ^_^
y = np.zeros(4)
y

array([0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [28]:
# write your code here ^_^
result = x + y
result

array([1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [40]:
# write your code here ^_^

x.ndim
x.shape
x.size
x.dtype

dtype('float64')

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [42]:
# write your code here ^_^
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [68]:
# write your code here ^_^
z = np.array([[1,2,3],[1,2,3],[1,2,3]])
z

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [74]:
# write your code here ^_^
newArray = np.hstack((w,z))
newArray

array([[11, 12,  1,  2,  3],
       [13, 14,  1,  2,  3],
       [15, 16,  1,  2,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [80]:
# write your code here ^_^
for i in newArray:
    print(i)
#--------------------
for i in newArray:
    for j in i:
        print(j)

11
12
1
2
3
13
14
1
2
3
15
16
1
2
3


## Q#9: Reverse the columns and rows of "newArray".

In [88]:
# write your code here ^_^
reverse = np.fliplr(newArray)
reverse

array([[ 3,  2,  1, 12, 11],
       [ 3,  2,  1, 14, 13],
       [ 3,  2,  1, 16, 15]])

## Q#10: Decrement all elements of "newArray" with 1.

In [90]:
# write your code here ^_^
decrement = newArray -1
decrement

array([[10, 11,  0,  1,  2],
       [12, 13,  0,  1,  2],
       [14, 15,  0,  1,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [102]:
# write your code here ^_^
smallest = np.min(newArray)
smallest
biggest = np.max(newArray)
biggest

1

## Q#12: Print the first row of "newArray" using indexing.

In [104]:
# write your code here ^_^
first_row = newArray[0]
first_row

array([11, 12,  1,  2,  3])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [114]:
# write your code here ^_^
for i in newArray:
    if np.where(newArray == 12):
        print(newArray)

IndexError: index 11 is out of bounds for axis 0 with size 3

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [ ]:
# write your code here ^_^

## Q#15: Change the shape of "newArray" to (9,1).

In [116]:
# write your code here ^_^
shape_change = newArray.reshape((9, 1))

ValueError: cannot reshape array of size 15 into shape (9,1)

## Q#16: Change the shape of "newArray" to (3,2).

In [118]:
# write your code here ^_^
shape_change2 = newArray.reshape((3, 2))

ValueError: cannot reshape array of size 15 into shape (3,2)

# Well Done 🎉